### ISSUE TITLE
smatch: too many mismatches in shallow liver test dataset

### ISSUE THREAD

**Issue by gesavoigt** [seqscope/NovaScope#13]
I am trying to run the NovaScope pipeline using the available test dataset of the liver shallow sequencing. After step `smatch`, I wanted to evaluate the output and found that almost all R1 HDMIs had been classified as mismatches. 

Here is the `summary.tsv`:
```
Type    Reads   Fraction
Total   11051480        1.00000
Miss    11051456        1.00000
Match   24      0.00000
Unique  2       0.00000
Dup(Exact)      22      0.00000
```

The two unique matches look like this in the `match.sorted.uniq.tsv.gz` file:
```
ATTGATGTTATAAGACAGGCCACGGGACCTT 1       1       1389704 1396869 3       5
GCTGTTCTACTCCTGGCTGATAATCGTATGC 1       1       943720  1524859 4       19
```
Correspondingly, the png is empty.

In the previous step, the `manifest.tsv` still reported plenty of barcodes to be matched:
```
id      filepath        barcodes        matches mismatches      xmin    xmax    ymin    ymax
1_1     1_1.sbcds.sorted.tsv.gz 5962994 5962994 0       0       1469211 0       2277916
```

To my knowledge, I used all parameters as described in the documentation.
My config_job.yaml looks like this:
```
## Input
input:
  flowcell: 9203-AP                       
  chip: B08C                               
  species: "mouse"                      
  seq1st:                                       
    fastq: "/gpfs/bwfor/work/ws/hd_fz305-seqscope/data/novascope_liver_shallow/B08Ctest/seq1st/fastqs/9203-AP.L3.2456_2556.R1_001.fastq.gz"          
    layout: "/gpfs/bwfor/work/ws/hd_fz305-seqscope/data/novascope_liver_shallow/B08Ctest/seq1st/layout/B08Csub.layout.tsv"               
  seq2nd:                                       
    - id: liver_shallow                    
      fastq_R1: "/gpfs/bwfor/work/ws/hd_fz305-seqscope/data/novascope_liver_shallow/B08Ctest/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R1.fastq.gz" 
      fastq_R2: "/gpfs/bwfor/work/ws/hd_fz305-seqscope/data/novascope_liver_shallow/B08Ctest/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R2.fastq.gz" 
                    
## Output
output: "/gpfs/bwfor/work/ws/hd_fz305-seqscope/data/novascope_liver_shallow/results_novascope"                      
request:
  - smatch-per-chip                     

## Environment
env_yml: "/home/hd/hd_hd/hd_fz305/NovaScope/config_env.yaml" 

##  Additional Fields:

upstream:
  fastq2sbcd:
    format: DraI31
```

What am I missing here? Please note that the `smatch` runs fine, only the resulting low match count is the issue.

P.S.: Is the H&E image for this sample available somewhere? The documentation refers to it, but I couldn't find it.

**Comment by WQ-CHENG** [comment]
@gesavoigt Hi gesavoigt! Based on your YAML file, it appears that you downloaded and applied our minimal test dataset to NovaScope instead of the shallow liver dataset.

If you'd like to switch to our shallow liver dataset, which includes the H&E tif file, you can find it alongside the H&E file on Zenodo at [10.5281/zenodo.10840696](https://zenodo.org/records/10840696). We also have [instructions](https://seqscope.github.io/NovaScope/getting_started/access_data/#downloading-the-datasets) for downloading the shallow liver dataset, which may help you identify the 1st-seq and 2nd-seq files. Additional details are provided in the example YAML file for the shallow liver dataset [here](https://github.com/seqscope/NovaScope/blob/main/testrun/shallow_liver_section/config_job.yaml).

If you prefer to continue using the minimal test dataset, I believe the missing matches in your run are due to the `skip_sbcd` setting. Specifically, the minimal test dataset has been manually modified, so `skip_sbcd` must be set to 0 even though the format is DraI31 (see the example below). More details are available in [its example YAML file](https://github.com/seqscope/NovaScope/blob/main/testrun/minimal_test_run/config_job.yaml).

```
upstream:
  fastq2sbcd:
    format: DraI31
  smatch:
    skip_sbcd: 0
```

Please don't hesitate to let me know if anything is unclear or if there are any issues. 
Thank you!
W.
